/**
 * Fetch BSData/wh40k-10e data and generate embedded TypeScript data files.
 *
 * Usage: npx tsx scripts/fetch-data.ts
 *
 * Requires `gh` CLI authenticated with GitHub.
 */

import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { parseGameSystem, parseCatalogue } from "../src/lib/xml-parser.js";
import type { Unit } from "../src/types.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const ROOT = join(__dirname, "..");

const REPO = "BSData/wh40k-10e";

// ── Helpers ──────────────────────────────────────────────────────────────

interface TreeEntry {
  path: string;
  sha: string;
}

function fetchTree(): TreeEntry[] {
  const raw = execSync(
    `gh api repos/${REPO}/git/trees/main --jq '.tree[] | select(.path | test("\\\\.(cat|gst)$")) | "\\(.path)\\t\\(.sha)"'`,
    { encoding: "utf-8", maxBuffer: 10 * 1024 * 1024 }
  );
  return raw
    .trim()
    .split("\n")
    .filter(Boolean)
    .map((line) => {
      const [path, sha] = line.split("\t");
      return { path, sha };
    });
}

function fetchBlob(sha: string): string {
  const b64 = execSync(
    `gh api repos/${REPO}/git/blobs/${sha} --jq '.content'`,
    { encoding: "utf-8", maxBuffer: 50 * 1024 * 1024 }
  );
  return Buffer.from(b64.trim(), "base64").toString("utf-8");
}

// ── Codegen helpers ──────────────────────────────────────────────────────

function escapeForTemplate(s: string): string {
  // Escape backticks and ${} inside template literals
  return s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

function serializeUnit(u: Unit): string {
  return JSON.stringify(u, null, 2);
}

// ── Main ─────────────────────────────────────────────────────────────────

async function main() {
  console.log("Fetching file tree from BSData/wh40k-10e...");
  const tree = fetchTree();

  const gstFiles = tree.filter((e) => e.path.endsWith(".gst"));
  const catFiles = tree.filter((e) => e.path.endsWith(".cat"));

  console.log(`Found ${gstFiles.length} .gst file(s), ${catFiles.length} .cat file(s)`);

  // ── Parse game system (.gst) for shared rules ──
  const allRules: { name: string; description: string }[] = [];

  for (const gst of gstFiles) {
    console.log(`  Fetching ${gst.path}...`);
    const xml = fetchBlob(gst.sha);
    const result = parseGameSystem(xml);
    console.log(`    → ${result.rules.length} rules from ${result.name}`);
    for (const r of result.rules) {
      allRules.push({ name: r.name, description: r.description });
    }
  }

  // ── Parse catalogues (.cat) for units ──
  const allUnits: Unit[] = [];

  for (const cat of catFiles) {
    // Skip library files — they contain shared entries, not standalone units
    if (cat.path.includes("Library")) {
      console.log(`  Skipping library: ${cat.path}`);
      continue;
    }

    console.log(`  Fetching ${cat.path}...`);
    const xml = fetchBlob(cat.sha);
    const units = parseCatalogue(xml);
    console.log(`    → ${units.length} units`);
    allUnits.push(...units);
  }

  console.log(`\nTotal: ${allUnits.length} units, ${allRules.length} shared rules`);

  // ── Write src/data/units.ts ──
  const unitsPath = join(ROOT, "src", "data", "units.ts");
  const unitsContent = [
    "// Auto-generated by scripts/fetch-data.ts — do not edit manually",
    `// Generated: ${new Date().toISOString()}`,
    `// Source: https://github.com/${REPO}`,
    "",
    'import type { Unit } from "../types.js";',
    "",
    `export const UNITS: Unit[] = ${JSON.stringify(allUnits, null, 2)};`,
    "",
  ].join("\n");

  writeFileSync(unitsPath, unitsContent, "utf-8");
  console.log(`Wrote ${unitsPath} (${allUnits.length} units)`);

  // ── Write src/data/rules.ts ──
  const rulesPath = join(ROOT, "src", "data", "rules.ts");
  const rulesContent = [
    "// Auto-generated by scripts/fetch-data.ts — do not edit manually",
    `// Generated: ${new Date().toISOString()}`,
    `// Source: https://github.com/${REPO}`,
    "",
    "export const SHARED_RULES: { name: string; description: string }[] = " +
      JSON.stringify(allRules, null, 2) +
      ";",
    "",
  ].join("\n");

  writeFileSync(rulesPath, rulesContent, "utf-8");
  console.log(`Wrote ${rulesPath} (${allRules.length} rules)`);
}

main().catch((err) => {
  console.error("Fatal error:", err);
  process.exit(1);
});
